baseURL = 'https://docs.hyperspike.io/'
languageCode = 'en-us'
title = 'Hyperspike Documentation'
theme = 'hugo-theme-techdoc'

[params]
	title = 'Hyperspike Documentation'
	description = 'Hyperspike Documentation'
	author = 'Hyperspike'
	menu_style = "open-menu"

	logo = "images/logo.png"
	google_analytics_id = "G-LXLNG1QM3T" # Your Google Analytics tracking id
	# tag_manager_container_id = ""


	menu_exclusion = [
		"archives",
		"archive",
	]

#[menu]
#	[[menu.main]]
#		name = "Home"
#		url = "/"
#		weight = 1
#		identifier = 'home'
		# pre = "<i class='fa fa-heart'></i>&nbsp;"
